### ISSUE TITLE
Add License

### ISSUE THREAD

**Issue by flxholle** [varunpvp/android-web-app#1]
Could you please add a License to this repository, so that everyone is allowed to use your code for their own website.
Thank you

**Comment by varunpvp** [comment]
Sure will do that.

**Comment by flxholle** [comment]
Thank you @varunpvp 
When do you think, you have time to do this?

**Comment by varunpvp** [comment]
Hi @asdoi, I've added the License to code. 
Thanks.

**Comment by flxholle** [comment]
Thank you very much
